# Site settings
baseurl: "/cutie" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems:
   - jemoji
   - jekyll-redirect-from

# Metadata
keywords: "Hello world, boilerplate"
google-fonts: "Source+Sans+Pro:400,700"
google-fonts-subsets: "latin"
google-analytics: "UA-XXXXXXXX-1"

# Commonly used lingo
title: "Cutie"
location: "Philadelphia, PA, USA"
email: contact@example.com
description: > # this means to ignore newlines until the next colon
  Jelly beans pie bear claw jelly beans marshmallow. Cookie ice cream icing oat cake jelly-o ice cream topping cotton candy. Brownie bonbon icing. Cake sugar plum tart jujubes cookie. Tiramisu tiramisu candy bear claw chocolate bar pastry. Biscuit chocolate tiramisu tiramisu. Sesame snaps danish dragée sugar plum carrot cake bonbon pastry fruitcake chocolate cake. Soufflé jelly beans toffee lollipop jujubes candy. Tiramisu lollipop chocolate cake chocolate bar donut cake. Gummies halvah sweet roll brownie gingerbread ice cream. Topping jelly beans croissant cake icing brownie apple pie cotton candy. Gingerbread oat cake cupcake bear claw brownie. Tart caramels cheesecake topping.
handle: LabLayers
